In [86]:
import numpy as np

In [87]:
#create an array from list comprehension,even numbers from range 2-20
numbers = np.array ([x for x in range (2,21,2) ])
print(numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [88]:
#create 2-by-5 array,even integers in first row , odd in second
numbers2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(numbers2)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [89]:
# this will return the tuple with one value(number of items) as this is 1d array 
numbers.shape

(10,)

In [90]:
#first value is a num of dimentions second how many items in it 
numbers2.shape

(2, 5)

In [91]:
#all the items in numbers2
numbers2.size

10

In [92]:
#to get number of dimentions
numbers2.ndim

2

In [93]:
#how much memory was used for each number 
numbers2.itemsize

4

In [94]:
for row in numbers2:
    for column in row:
        print(column,end = ' ')
    print()    

2 4 6 8 10 
1 3 5 7 9 


In [95]:
#using flat atribute
for i in numbers2.flat:
    print (i , end = ' ')
    

2 4 6 8 10 1 3 5 7 9 

In [96]:
#this are floats 5 * 0.
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [97]:
ones_ints = np.ones((2,5),dtype = int)
print(ones_ints)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [98]:
#if i want any number 
num =np.full((3,5),13)
print(num)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


# lesson 148  arange

In [99]:
# function range in numpy is called arange (top value not included)
integers = np.arange(5,10)
integers
integers_in_reverse= np.arange(10,1,-1)
print(integers_in_reverse)
#floatining poit ranges (start,end(not included),total num of values to produce)
#he will equally devide into 5 nums and allign them
floats = np.linspace(0.0,1.0,num=5) 
floats

[10  9  8  7  6  5  4  3  2]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

_reshape_

In [100]:
shaping= np.arange(1,21).reshape(4,5) 
shaping

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [101]:
#elipsis notation when loads of numbers -> will show 3 first and 3 last with elipsis in the middle 
big_array = np.arange(1,100001).reshape(4,25000)
print(big_array)

[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]


EX 149 create array and reshape it

In [102]:
ex149 = np.arange(2,41,2).reshape(4,5)
print(ex149)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


#Lesson 150 comparing the speed of list vs numpy array 
_using magic timeit method_

In [103]:
import random
%timeit rolls_list = [random.randrange(1,7) for i in range(6_000_000)]


8.87 s ± 470 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [104]:
%timeit rolls_array = np.random.randint(1,7,6_000_000)

81.7 ms ± 2.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# ARRAY OPERATORS

In [105]:
#numpy will perform these operations element by element broadcasting 
numbers = np.arange(1,6)
print(numbers)
numbers * 2

[1 2 3 4 5]


array([ 2,  4,  6,  8, 10])

In [106]:
numbers +=10
print(numbers)

[11 12 13 14 15]


operations between arrays

In [107]:
numbers2 = np.linspace (1.1,5.5,5)
numbers2


array([1.1, 2.2, 3.3, 4.4, 5.5])

In [108]:
#also element by element will multiply 
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [109]:
#this will produce boolean values for each element in nparray
numbers >= 13

array([False, False,  True,  True,  True])

In [110]:
numbers == numbers2

array([False, False, False, False, False])

In [111]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [112]:
test = np.arange(1,6) **2
print(test)

[ 1  4  9 16 25]


# video 154 calculation methods

In [113]:
grades = np.array([[87,96,70],
                 [100,87,90],
                 [94,77,90],
                  [100,81,82],]
                 )
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [114]:
#this is working on the whole array
grades.sum()
grades.min()
grades.max()
grades.mean()
grades.std()
grades.var()

77.30555555555556

In [115]:
#to perform operations on columns we specify axis=0
#grades by exam 
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [116]:
#to go by rows axis=1
#grades by student
grades.mean(axis =1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

_vid 155 self check_ <br>create random grades 12 from range 60-100 <br>
reshape them to 3-by-4 array <br> show average for each column and each row

In [117]:
gr = np.random.randint(60,101,12).reshape(3,4)
print(gr)
grades_by_column = gr.mean(axis = 0)
grades_by_row = gr.mean(axis = 1)
print(grades_by_column)
print(grades_by_row)

[[64 64 89 61]
 [86 72 74 78]
 [80 66 67 76]]
[76.66666667 67.33333333 76.66666667 71.66666667]
[69.5  77.5  72.25]


#universal functions

In [118]:
#sqrt is an usniversal function
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [119]:
numbers2 =np.arange(1,7) * 7
numbers2

array([ 7, 14, 21, 28, 35, 42])

In [120]:
# add is an universal function
np.add (numbers , numbers2)

array([ 8, 18, 30, 44, 60, 78])

In [121]:
#multiply - universal function
np.multiply(numbers2,5)

array([ 35,  70, 105, 140, 175, 210])

## The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.<br> Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [122]:
numbers3 = numbers2.reshape(2,3)
print(numbers3)
numbers4 = np.array([2,4,6])
print(numbers4)

[[ 7 14 21]
 [28 35 42]]
[2 4 6]


In [123]:
np.multiply(numbers3,numbers4)

array([[ 14,  56, 126],
       [ 56, 140, 252]])

In [124]:
#cube the numbers from 1-5 using universal function 
numbers5 =np.arange(1,6)
np.power(numbers5,3)

array([  1,   8,  27,  64, 125], dtype=int32)

# vid 158 indexing and slicing

In [125]:
grades = np.array([[87,96,70],
                 [100,87,90],
                 [94,77,90],
                  [100,81,82],]
                 )
grades[0,1]

96

In [126]:
grades[1]

array([100,  87,  90])

In [127]:
#slice from zero to 2 not included
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [128]:
#to get individual rows that are not contigues
#just row number 1 & row number 3 ->passing a list of rows we want as an argument 
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [129]:
#to work with columns 
#all the rows just column 0
grades[:,0]

array([ 87, 100,  94, 100])

In [130]:
new_list = np.array([1,2,3,4,5])
print(new_list)

[1 2 3 4 5]


_vid 159_ from the array <br>select second row <br> select 1st and 3rd rows <br>select middle 3 columns

In [131]:
arr159 =np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr159)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [132]:
arr159[1]

array([ 6,  7,  8,  9, 10])

In [133]:
arr159[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [134]:
arr159[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

# vid 162 reshape resize

Both reshape and resize change the shape of the numpy array;<br> the difference is that using resize will affect the original array <br>while using reshape create a new reshaped instance of the array.

In [135]:
#like with strings not changing oryginal making new one
arr159.reshape(1,15)

print(arr159)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [136]:
# changes the oryginal one
resize = arr159.resize(1,15)
print(arr159)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


# vid 163 flatten and ravel <br> flatten -deep copy , ravel - shallow copy (view)

In [137]:
arr159 =np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr159)

flattened = arr159.flatten()
flattened[0] = 100
print(flattened)
print(flattened.base)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
None


In [138]:
#flatten wont affect the oryginal data (owns his data )
arr159

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [139]:
# if u dont need the full copy of data you can use ravel its the view in 1 dimension
raveled = arr159.ravel()
raveled[0] = 2000
print(raveled)
print(raveled.base)

[2000    2    3    4    5    6    7    8    9   10   11   12   13   14
   15]
[[2000    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]]


In [140]:
#ravel is a view so it will modify the oryginal data 
#any changes made in oryginal will show up in ravel
arr159

array([[2000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15]])

In [141]:
arr159[1] = 1000
print(raveled)

[2000    2    3    4    5 1000 1000 1000 1000 1000   11   12   13   14
   15]


In [142]:
arr159

array([[2000,    2,    3,    4,    5],
       [1000, 1000, 1000, 1000, 1000],
       [  11,   12,   13,   14,   15]])

# transposing changing columns into rows and rows into columns

In [143]:
arr159 =np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr159)
arr159.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# horizontal and verdical stacking 

In [152]:
grades1 =np.array([[10,20,30],[40,50,60]])
print(grades1)
grades2= np.array([[99,88,77],[66,55,44]])
print(grades2)

[[10 20 30]
 [40 50 60]]
[[99 88 77]
 [66 55 44]]


In [151]:
# u pass a tuple to this method 
np.hstack((grades1,grades2))


array([[10, 20, 30, 99, 88, 77],
       [40, 50, 60, 66, 55, 44]])

In [150]:
np.vstack((grades1,grades2))

array([[10, 20, 30],
       [40, 50, 60],
       [99, 88, 77],
       [66, 55, 44]])

_vid 166_ <br>use h stack and v stack 

In [163]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
a = np.hstack((a,a))
a = np.vstack((a,a))


NameError: name 'np' is not defined