![Numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

### Numpy Review 1
#### Numpy Atributes
1. *dtype*
2. *ndim* 
3. *shape*
4. *size*
---


In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4],[5,6,7,8,]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**show the data type of the ndarray**<br>
Numpy arrays cointain homogenous data - Data of the same type.<br>
<font color ='magenta'> We cannot have mixture of data types ( int,str,float )</font>

In [4]:
arr1.dtype

dtype('int32')

**show the dimensions of the ndarray**<br>
Numpy arrays can be multi-dimentional

In [6]:
arr1.ndim

2

**show the shape of the ndarray**<br>
Use shape to show the shape of the array<br>
<font color = 'magenta'> Each array in the second dimention must have the same number of items</font>

In [19]:
arr1.shape

(2, 4)

**show the size of the ndarray**<br>
Show how many elements are in the array<br>
<font color = 'magenta'> doesnt matter what shape the array is</font>

In [21]:
arr1.size

8

**show the amout of memory being used for each element in  ndarray**<br>
This is the number of bytes that each value takes up in memory <br>
<font color = 'magenta'> different data types use diferent amount of memory  is</font>

In [22]:
arr1.itemsize

4

### Numpy Review 2
#### Filling an NumPy array with values
1. *arange*
2. *random numbers* 
3. *linspace*
4. *zeros*
3. *full*
4. *reshape vs resize*
---


In [29]:
# even numbers from 1 to 100
arr2 = np.arange(0,1001,2)
print(arr2)
print (f'There is {arr2.size} elements in this array, all the elements are of type {arr2.dtype}')

[   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386  388  390
  392 

In [39]:
# create an array and reshape it
arr3 = np.arange(0,50).reshape(5,10)
arr3    

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
# flatten the array 
print(arr3.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [50]:
ones1 = np.ones(50,dtype = int).reshape(10,5)
print(ones1)
print(ones1.ndim)
print(ones1.size)
print(ones1.dtype)
print(ones1.itemsize)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2
50
int32
4


In [56]:
zeros1=np.zeros(10)
zeros1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
# as default they come as floats
ones1 = np.ones(50 ,dtype = int).reshape(10,5)
ones1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
#he will equally devide into 5 nums and allign them
nums = np.linspace(1,8,num = 5) 
nums

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [59]:
# 30 random numbers between 0.0 - 1.0
floats1 = np.random.rand(30)
print(floats1)
print('***********************')
# 30 random numbers between 0 - 20
floats2 = np.random.rand(30)*20
print(floats2)

[0.41371821 0.27308117 0.03114901 0.14198654 0.03669419 0.22134309
 0.24639618 0.64665316 0.05928353 0.36768918 0.62871743 0.24438495
 0.73575063 0.21744553 0.44802789 0.2363131  0.62087602 0.10281805
 0.081003   0.09401075 0.42943962 0.83690034 0.58112464 0.24375232
 0.31435725 0.55553563 0.36129212 0.44601437 0.22520429 0.85652054]
***********************
[1.66650183e+01 5.22738607e+00 1.24441142e+01 5.47908342e+00
 8.50731836e+00 1.99975752e+01 1.38780342e+01 1.65658259e+01
 1.10726237e+01 1.74949653e-02 6.32946640e+00 1.85877980e+01
 1.63264577e+01 1.22269842e+01 1.73736554e+01 1.44967512e+01
 1.96907171e+01 7.79593448e+00 2.70396221e+00 1.48713393e+01
 1.19244997e+00 1.70963385e+01 1.67209492e+01 9.58461783e+00
 1.97840481e-01 1.33977266e+01 5.06415516e+00 1.61724993e+01
 1.31210167e+01 1.94596410e+00]


In [61]:
# 30 random integers from 1 to 1-100
ints1 = np.random.randint(1,101,30)
print(ints1)

[ 8 98  2 51  3 37 15 96 67 16 23 78 20 29 80 34 71 23 30  2 52 64 51 47
 37 45 70 90  1 71]


In [63]:
#seed the random number generator 
np.random.seed(12)
ints2 = np.random.randint(1,15,10)
ints2

array([12, 12,  7, 14,  2,  3,  4,  4, 13,  1])

In [66]:
x= np.random.randint(50,151,24).reshape(6,4)
x

array([[134,  56, 123,  95],
       [ 80,  82,  77, 109],
       [139, 109, 138, 129],
       [ 75, 147, 106,  54],
       [146, 118, 115,  94],
       [ 87, 125, 118, 103]])

In [80]:
# 
y = np.random.randint(100,151,size = (6,4))
y

array([[142, 107, 111, 139],
       [134, 131, 103, 148],
       [134, 142, 129, 137],
       [110, 128, 128, 120],
       [145, 103, 146, 147],
       [128, 116, 141, 117]])

In [81]:
# 2x3 array with random ints between 0-4
z = np.random.randint(5,size = (2,3,2))
z

array([[[0, 4],
        [0, 2],
        [0, 1]],

       [[1, 2],
        [1, 3],
        [2, 0]]])

In [82]:
# getting 1d array
z_flatten=z.reshape(-1)
z_flatten

array([0, 4, 0, 2, 0, 1, 1, 2, 1, 3, 2, 0])